# Generated by Django 2.0.10 on 2019-01-10 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='candidates',
        ),
    ]
