# Generated by Django 2.0.10 on 2019-01-10 04:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('performances', '0002_remove_team_candidates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performance',
            options={'ordering': ('-timeslot',)},
        ),
        migrations.AddField(
            model_name='performance',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performances', to='performances.Team'),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterUniqueTogether(
            name='performance',
            unique_together={('performer', 'song', 'team')},
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('mentor', 'performance')},
        ),
    ]
